# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NbCell": "00_read.ipynb",
         "dict2nb": "00_read.ipynb",
         "read_nb": "00_read.ipynb",
         "nbdev_create_config": "00_read.ipynb",
         "update_version": "00_read.ipynb",
         "add_init": "00_read.ipynb",
         "cell_header": "00_read.ipynb",
         "export_cells": "00_read.ipynb",
         "create_all_cell": "00_read.ipynb",
         "extract_comments": "01_export.ipynb",
         "NotebookProcessor": "01_export.ipynb",
         "NotebookProcessor.process_comment": "01_export.ipynb",
         "NotebookProcessor.process_cell": "01_export.ipynb",
         "NotebookProcessor.no_cmd": "01_export.ipynb",
         "NotebookProcessor.process": "01_export.ipynb",
         "ModuleMaker": "01_export.ipynb",
         "retr_exports": "01_export.ipynb",
         "ModuleMaker.make_all": "01_export.ipynb",
         "relative_import": "01_export.ipynb",
         "absolute_import": "01_export.ipynb",
         "update_import": "01_export.ipynb",
         "NbCell.import2relative": "01_export.ipynb",
         "ModuleMaker.make": "01_export.ipynb",
         "find_var": "01_export.ipynb",
         "read_var": "01_export.ipynb",
         "update_var": "01_export.ipynb",
         "ExportModuleProcessor": "01_export.ipynb",
         "ExportModuleProcessor.default_exp_code": "01_export.ipynb",
         "ExportModuleProcessor.exporti_code": "01_export.ipynb",
         "ExportModuleProcessor.export_code": "01_export.ipynb",
         "ExportModuleProcessor.exports_code": "01_export.ipynb",
         "ExportModuleProcessor.create_modules": "01_export.ipynb",
         "nbdev_build_lib": "01_export.ipynb",
         "mod_fn2name": "01a_doclinks.ipynb",
         "DocLinks": "01a_doclinks.ipynb",
         "DocLinks.create_nbdev_idx_tmpl": "01a_doclinks.ipynb",
         "DocLinks.update_mods": "01a_doclinks.ipynb",
         "DocLinks.update_syms": "01a_doclinks.ipynb",
         "nbdev_update_lib": "02_sync.ipynb",
         "type_repr": "03_showdoc.ipynb",
         "format_param": "03_showdoc.ipynb",
         "show_doc": "03_showdoc.ipynb",
         "get_doc_link": "03_showdoc.ipynb",
         "doc": "03_showdoc.ipynb",
         "nbdev_diff_nbs": "09_cli.ipynb",
         "nbdev_trust_nbs": "09_cli.ipynb",
         "say_hello": "tutorial.ipynb",
         "HelloSayer": "tutorial.ipynb"}

modules = ["read.py",
           "export.py",
           "sync.py",
           "showdoc.py",
           "cli.py",
           "tutorial.py"]

doc_url = "https://nbdev.fast.ai/"

git_url = "https://github.com/fastai/nbdev/tree/master/"

def custom_doc_links(name): return None
